apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCV/+D+kyHUErqm8JYIfmffslKfcDUynKKUBWprGtH65dAD4LBBwTtShHWzsV0Z7iwVLwvs7dkAgTlH2eaTKuK2G669l/VV5OOj8jz2/CDRp0Bg2etKcZaYOfsO/wWWu6fxXZFXvp7njX82FjaS2Ns0KAezAEgIoiEtxSFAbRdoFDjIAju6EmB3HGfiTjq7anCXiGyRqej8Vyk7ay9ZQcTUpM+PzsRVIirN5qVvtjvoLZr1KZiQIJp7USUD0iSctScQukKoTXqJA+0AHH1elnIvdwQkC361cEEBiB3Fx6yuuQqoyBNB2TRS13JmjdPWXms+q4xsT4Yz/21c9A5oT+1zP6f3dv69tzzLxDtfYAaDIRP5C8R+niVdKZzgebqJyAFrJCa+750iGLk2Vwa3SVpboIQwtNRRmzGK4cYrOQE7BcVsk+dKlz64up+zwLr12UBFCmJVMTWUzPfjkdWJ7JsFwLuc076KSYqNRX4EnhZkie/y2n8NGiQvcNTKajwmEoTTpjY1eRwPqBc+n4Y3Hm027mAQwpA+GW1WroaNiJzhcpeAg80IbTu7TC4/AKmTCojfR0PlDJxlk0VCPBk83b7lyi8crw1USzkZ8eKDAsqhQTkATYy9pXBv+gGU8+hHlidRBT6sBAnV92r+6lYmpbBzHiwUkcwTxTZ7oVygvynDlRoLcnfaz04aMOu71HxXH027ApB0e9XmgNjrjeO/G1LlQ4siMgIgWx12cdorFM9tcf96Uhg97aWyAy71jqVdeESPn9mePHKNj0+kLX6DEpEDT/Iu4z0ZwrCn8mzCZLzrr2e7FeydRNrGu7gD0gRimy9kKpOqHO7ghd0qx28eaL1WgTcww5akbKavDrK8fUPzdxd5xgbBTcSgq5zpcsf5gzBE3EFtlcQ4GOt8Ipkih6PhrYat5BDlbvovh7g6gYBe2s0c7B5545v33SVcn/UaVgH3Mz2qHP6fJdMKFde+Wzw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

