apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: charts/argo-workflows
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        server: 
          ingress:
            hosts:
              - argo-workflows.production.ibus-dev.es-si-os-gsn-28.k8s.dyn.nesc.nokia.net
            enabled: true
            ingressClassName: nginx
        controller:
          containerRuntimeExecutor: emissary
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

